# Generated by Django 5.1.7 on 2025-03-17 22:48

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a cat breed (e.g. Siamese, Maine Coon, British Shorthair, Moggie, etc.)', max_length=200, unique=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='breed_name_case_insensitive_unique', violation_error_message='Breed already exists (case insensitive match)')],
            },
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description of the cat', max_length=1000)),
                ('nickname', models.CharField(help_text='Made up nickname for the cat when we do not know its actual name', max_length=50, verbose_name='Nickname')),
                ('breed', models.ManyToManyField(help_text='Select a breed', to='catalog.breed')),
            ],
        ),
    ]
