# Generated by Django 5.1.7 on 2025-03-17 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='breed',
        ),
        migrations.AlterField(
            model_name='cat',
            name='nickname',
            field=models.CharField(help_text='Made up nickname for the cat when we do not know its actual name', max_length=150, verbose_name='Nickname'),
        ),
        migrations.AddField(
            model_name='cat',
            name='breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.breed'),
        ),
    ]
