# Generated by Django 5.1.7 on 2025-03-17 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.cat'),
        ),
    ]
